# Generated by Django 2.2.10 on 2020-07-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedsurvey',
            name='answers',
        ),
        migrations.AddField(
            model_name='completedsurvey',
            name='answers',
            field=models.ManyToManyField(related_name='answer_completed_surveys', to='survey.Answer'),
        ),
    ]
