# Generated by Django 2.2.10 on 2020-07-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('text', 'Text'), ('one', 'One'), ('many', 'Many')], max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('ex_user', 'question')},
        ),
    ]
