# Generated by Django 2.2.10 on 2020-07-06 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200707_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ex_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.ExtendedUser'),
        ),
    ]
